name: CI/CD

on:
  push:
    branches: [ master ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  # Phase 1: Parallel Jobs
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          cmake-version: 3.22.1
          ndk-version: 26.1.10909125

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test
        env:
          GRADLE_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"

  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          cmake-version: 3.22.1
          ndk-version: 26.1.10909125

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleStableRelease
        env:
          GRADLE_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: java/build/outputs/apk/stable/release/*.apk
          retention-days: 1

  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          cmake-version: 3.22.1
          ndk-version: 26.1.10909125

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleUnstableDebug
        env:
          GRADLE_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: java/build/outputs/apk/unstable/debug/*.apk
          retention-days: 1

  # Phase 2: Release Job (only after all Phase 1 jobs pass)
  create-release:
    runs-on: ubuntu-latest
    needs: [test, build-release-apk, build-debug-apk]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version from commit
        id: version
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="v1.0.${COMMIT_COUNT}"
          TAG_NAME="auto-release-${COMMIT_COUNT}-${SHORT_SHA}"
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Download release APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: ./release-apks/

      - name: Download debug APK
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: ./debug-apks/

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" -5)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          name: "${{ steps.version.outputs.VERSION }}"
          body: |
            ## 🚀 Auto-Generated Release ${{ steps.version.outputs.VERSION }}
            
            **Built from commit:** `${{ github.sha }}`
            
            ### Recent Changes
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ### Installation
            1. Download the APK below
            2. Enable keyboard in Android settings
            
            ### Build Info
            - ✅ Tests passed
            - ✅ Release APK built successfully  
            - ✅ Debug APK built successfully
          draft: false
          prerelease: false
          files: |
            ./release-apks/*.apk
            ./debug-apks/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}